spring:
  messages:
    basename: i18n/validate  #   验证文件的路径
  profiles:
    active: dev
  jackson:
    date-format: yy-MM-dd HH:mm:ss  #统一进行日期格式的数据返回
    time-zone: Asia/Shanghai   # 默认时区
  datasource:
    url: jdbc:mysql://47.112.217.144:3306/pc_repair?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false   # 数据库的时区地址
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #  下划线转换程驼峰
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #  日志也可以这么配置
  mapper-locations: classpath*:mybatis/mapper/**/*.xml  # mapper.xml文件的路径配置com.mpic.evolution.chair.dao
logging:
  level:
    com.wxcz.carpenter.dao: debug
server:
  port: 80

